// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID                 int64
	Name               string
	Place              string
	Status             string
	Link               string
	Date               time.Time
	Artist             sql.NullString
	Category           sql.NullString
	ArtistUrl          sql.NullString
	ArtistImgUrl       sql.NullString
	ReportedAtNew      sql.NullTime
	ReportedAtUpcoming sql.NullTime
	CreatedAt          time.Time
}
